-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 6
-- Name:    50 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 6.

CREATE TABLE IF NOT EXISTS "app_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_name" TEXT NOT NULL,
  "user_role" TEXT,
  "event_type" TEXT NOT NULL,
  "widget_id" TEXT,
  "widget_title" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "metric_disputes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "metric_id" INTEGER NOT NULL,
  "ticket_ref" TEXT,
  "submitted_by" TEXT NOT NULL,
  "field_name" TEXT NOT NULL,
  "original_value" REAL,
  "proposed_value" REAL,
  "reason" TEXT NOT NULL,
  "evidence_note" TEXT,
  "attachments_json" TEXT,
  "status" TEXT NOT NULL,
  "reviewed_by" TEXT,
  "review_note" TEXT,
  "reviewed_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "ticket_number" TEXT;

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "raw_notes" TEXT NOT NULL;

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "subject" TEXT;

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "mode" TEXT;

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "to_emails" TEXT;

ALTER TABLE "escalation_drafts" ADD COLUMN IF NOT EXISTS "carrier_id" TEXT;

ALTER TABLE "manager_updates" ADD COLUMN IF NOT EXISTS "priority" TEXT NOT NULL;

ALTER TABLE "manager_updates" ADD COLUMN IF NOT EXISTS "expires_at" TEXT;

ALTER TABLE "performance_imports" ADD COLUMN IF NOT EXISTS "sheet_name" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "source_type" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "total_count" INTEGER;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "period_start" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "queue" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "period_month" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "period_quarter" TEXT;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "ack_minutes" REAL;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "carrier_ticket_minutes" REAL;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "handle_seconds" REAL;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "wait_seconds" REAL;

ALTER TABLE "performance_metrics" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "audience" TEXT NOT NULL;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "recipient_name" TEXT;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "raw_draft" TEXT NOT NULL;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "subject" TEXT;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "tone" TEXT;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "length" TEXT;

ALTER TABLE "polished_emails" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "shift_name" TEXT NOT NULL;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "tickets_json" TEXT;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "team" TEXT NOT NULL;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE "user_roles" ADD COLUMN IF NOT EXISTS "email" TEXT;

ALTER TABLE "user_roles" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL;

ALTER TABLE "user_roles" ADD COLUMN IF NOT EXISTS "updated_by" TEXT;

ALTER TABLE "user_roles" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE "user_sessions" ADD COLUMN IF NOT EXISTS "email" TEXT;

ALTER TABLE "user_sessions" ADD COLUMN IF NOT EXISTS "sign_in_method" TEXT NOT NULL;

ALTER TABLE "user_sessions" ADD COLUMN IF NOT EXISTS "picture" TEXT;

ALTER TABLE "user_sessions" ADD COLUMN IF NOT EXISTS "last_sign_in" TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE "escalation_drafts" ALTER COLUMN "sender_name" DROP NOT NULL;

ALTER TABLE "performance_imports" ALTER COLUMN "source_type" DROP NOT NULL;

ALTER TABLE "performance_metrics" ALTER COLUMN "raw_json" DROP DEFAULT;

ALTER TABLE "polished_emails" ALTER COLUMN "sender_name" DROP NOT NULL;

ALTER TABLE "polished_emails" ALTER COLUMN "body_markdown" DROP DEFAULT;

ALTER TABLE "team_members" ALTER COLUMN "tier" DROP DEFAULT;

ALTER TABLE "user_roles" ALTER COLUMN "name" DROP DEFAULT;

ALTER TABLE "user_sessions" ALTER COLUMN "name" DROP DEFAULT;
