-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 7
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 7.

CREATE TABLE IF NOT EXISTS "wfh_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "start_date" TEXT NOT NULL,
  "end_date" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "submitted_at" TEXT NOT NULL,
  "reviewed_by" TEXT,
  "reviewed_at" TEXT,
  "decision_note" TEXT,
  "slack_message_ts" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
