-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 8
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 8.

CREATE TABLE IF NOT EXISTS "zoom_queue_snapshots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "agent_id" TEXT NOT NULL,
  "agent_name" TEXT NOT NULL,
  "queue_name" TEXT NOT NULL,
  "receive_call" BOOLEAN NOT NULL,
  "snapshot_date" TEXT NOT NULL,
  "snapshot_hour" INTEGER NOT NULL,
  "snapshot_time" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
