-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 9
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 9.

CREATE TABLE IF NOT EXISTS "ticket_audits" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_size_bytes" INTEGER NOT NULL,
  "ticket_number" TEXT,
  "ticket_subject" TEXT,
  "agent_name" TEXT,
  "agent_name_raw" TEXT,
  "overall_score" REAL,
  "grade" TEXT,
  "criteria_json" TEXT,
  "analysis_markdown" TEXT NOT NULL,
  "audit_month" TEXT,
  "queue" TEXT,
  "audited_by" TEXT,
  "metrics_id" INTEGER,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
