-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 10
-- Name:    3 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 10.

ALTER TABLE "ticket_audits" ADD COLUMN IF NOT EXISTS "ticket_date" TEXT;

ALTER TABLE "ticket_audits" ADD COLUMN IF NOT EXISTS "what_did_well" TEXT;

ALTER TABLE "ticket_audits" ADD COLUMN IF NOT EXISTS "what_missed" TEXT;
