-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 11
-- Name:    2 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 11.

CREATE TABLE IF NOT EXISTS "training_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "requester_name" TEXT NOT NULL,
  "requester_email" TEXT,
  "training_title" TEXT NOT NULL,
  "training_type" TEXT NOT NULL,
  "due_date" TEXT,
  "details" TEXT,
  "status" TEXT NOT NULL,
  "manager_note" TEXT,
  "reviewed_by" TEXT,
  "reviewed_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "upcoming_trainings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "training_date" TEXT NOT NULL,
  "audience" TEXT NOT NULL,
  "posted_by" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
