-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 12
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 12.

CREATE TABLE IF NOT EXISTS "break_schedules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "schedule_type" TEXT NOT NULL,
  "schedule_date" TEXT,
  "start_time" TEXT NOT NULL,
  "end_time" TEXT NOT NULL,
  "updated_by" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
