-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 13
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 13.

CREATE TABLE IF NOT EXISTS "reminder_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "reminder_type" TEXT NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "sent_at" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
