-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 14
-- Name:    2 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 14.

CREATE TABLE IF NOT EXISTS "one_on_one_notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "manager_name" TEXT NOT NULL,
  "employee_name" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "meeting_date" TEXT,
  "source_type" TEXT NOT NULL,
  "source_message_id" TEXT,
  "source_subject" TEXT,
  "source_excerpt" TEXT,
  "source_body" TEXT,
  "summary_markdown" TEXT NOT NULL,
  "discussion_points_json" TEXT,
  "manager_action_items_json" TEXT,
  "employee_action_items_json" TEXT,
  "status" TEXT NOT NULL,
  "shared_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "personal_action_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "note_id" INTEGER,
  "title" TEXT NOT NULL,
  "details" TEXT,
  "status" TEXT NOT NULL,
  "due_date" TEXT,
  "created_by" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
