-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 15
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 15.

CREATE TABLE IF NOT EXISTS "google_account_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "google_sub" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "name" TEXT,
  "access_token" TEXT,
  "refresh_token" TEXT,
  "token_type" TEXT,
  "granted_scopes" TEXT,
  "expires_at" TEXT,
  "updated_at" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
