-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 16
-- Name:    9 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 16.

CREATE TABLE IF NOT EXISTS "notebook_section_preferences" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "owner_name" TEXT NOT NULL,
  "notebook_group" TEXT NOT NULL,
  "section_key" TEXT NOT NULL,
  "section_label" TEXT NOT NULL,
  "is_favorite" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "notebook_group" TEXT;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "section_name" TEXT;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "parent_note_id" INTEGER;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "sort_order" INTEGER;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "is_favorite" BOOLEAN;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "is_archived" BOOLEAN;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "archived_at" TEXT;

ALTER TABLE "one_on_one_notes" ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
