-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 17
-- Name:    5 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 17.

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "owner_name" TEXT;

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "priority" TEXT;

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "progress_percent" INTEGER;

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "section_name" TEXT;

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "notebook_group" TEXT;
