-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 18
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 18.

ALTER TABLE "personal_action_items" ADD COLUMN IF NOT EXISTS "blocked_by_id" INTEGER;
