-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 19
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 19.

CREATE TABLE IF NOT EXISTS "kb_gaps" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "question" TEXT NOT NULL,
  "reported_by" TEXT NOT NULL,
  "ai_response" TEXT,
  "status" TEXT NOT NULL,
  "resolved_by" TEXT,
  "resolution_note" TEXT,
  "confluence_url" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "kudos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "from_name" TEXT NOT NULL,
  "to_name" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "is_pinned" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "shift_checklist_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "agent_name" TEXT NOT NULL,
  "shift_date" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "item_text" TEXT NOT NULL,
  "is_done" BOOLEAN NOT NULL DEFAULT false,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "training_completions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "training_id" INTEGER NOT NULL,
  "agent_name" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "completed_at" TEXT,
  "note" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
