-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 21
-- Name:    10 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 21.

CREATE TABLE IF NOT EXISTS "punch_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "message" TEXT,
  "slack_posted" BOOLEAN,
  "slack_channel" TEXT,
  "slack_ts" TEXT,
  "punched_at" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "bridges_json" TEXT;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "active_service_note" TEXT;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "rolling_handoff_note" TEXT;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "is_weekend_holiday" BOOLEAN;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "new_tickets_count" INTEGER;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "p1_p2_count" INTEGER;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "shift_occupancy" TEXT;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "idle_time_note" TEXT;

ALTER TABLE "shift_handovers" ADD COLUMN IF NOT EXISTS "submitted" BOOLEAN;
