-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 22
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 22.

ALTER TABLE "ticket_audits" ADD COLUMN IF NOT EXISTS "audit_role" TEXT;
