-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 23
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 23.

CREATE TABLE IF NOT EXISTS "calendar_meetings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT NOT NULL,
  "calendar_event_id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "start_at" TEXT NOT NULL,
  "end_at" TEXT NOT NULL,
  "timezone" TEXT,
  "status" TEXT NOT NULL,
  "html_link" TEXT,
  "join_link" TEXT,
  "provider" TEXT,
  "location" TEXT,
  "source_hash" TEXT,
  "last_synced_at" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "meeting_reminder_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT NOT NULL,
  "calendar_event_id" TEXT NOT NULL,
  "meeting_start_at" TEXT NOT NULL,
  "reminder_offset_minutes" INTEGER NOT NULL,
  "scheduled_for" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "slack_target_type" TEXT,
  "slack_target_id" TEXT,
  "join_link" TEXT,
  "payload_json" TEXT,
  "attempt_count" INTEGER,
  "last_error" TEXT,
  "next_attempt_at" TEXT,
  "locked_at" TEXT,
  "locked_by" TEXT,
  "sent_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "notification_targets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "channel_type" TEXT NOT NULL,
  "slack_user_id" TEXT,
  "slack_channel_id" TEXT,
  "enabled" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reminder_policies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "meeting_enabled" BOOLEAN NOT NULL,
  "offset_30_enabled" BOOLEAN NOT NULL,
  "offset_15_enabled" BOOLEAN NOT NULL,
  "offset_5_enabled" BOOLEAN NOT NULL,
  "only_with_join_link" BOOLEAN NOT NULL,
  "timezone" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
