-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 25
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 25.

CREATE TABLE IF NOT EXISTS "calendar_meetings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "calendar_event_id" TEXT NOT NULL,
  "title" TEXT,
  "description" TEXT,
  "location" TEXT,
  "start_at" TEXT NOT NULL,
  "end_at" TEXT,
  "join_link" TEXT,
  "provider" TEXT,
  "status" TEXT,
  "raw_json" TEXT,
  "synced_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "meeting_reminder_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "calendar_event_id" TEXT NOT NULL,
  "meeting_start_at" TEXT NOT NULL,
  "reminder_offset_minutes" INTEGER NOT NULL,
  "scheduled_for" TEXT NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "join_link" TEXT,
  "payload_json" TEXT,
  "status" TEXT NOT NULL,
  "attempt_count" INTEGER,
  "last_error" TEXT,
  "sent_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "notification_targets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "channel_type" TEXT NOT NULL,
  "slack_user_id" TEXT,
  "slack_channel_id" TEXT,
  "enabled" BOOLEAN,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "reminder_policies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "employee_email" TEXT,
  "timezone" TEXT,
  "meeting_enabled" BOOLEAN,
  "offset_30_enabled" BOOLEAN,
  "offset_15_enabled" BOOLEAN,
  "offset_5_enabled" BOOLEAN,
  "only_with_join_link" BOOLEAN,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
