-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 26
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 26.

CREATE TABLE IF NOT EXISTS "training_comments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "training_id" INTEGER NOT NULL,
  "author_name" TEXT NOT NULL,
  "author_role" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "progress_percent" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "target_date" TEXT;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
