-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 27
-- Name:    7 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 27.

CREATE TABLE IF NOT EXISTS "training_certifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "certification" TEXT NOT NULL,
  "badge" TEXT NOT NULL,
  "holder_name" TEXT NOT NULL,
  "issuer" TEXT,
  "cert_id" TEXT,
  "issue_date" TEXT,
  "expires_on" TEXT,
  "proof_link" TEXT,
  "proof_file_url" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "renewed_from_id" INTEGER,
  "created_by" TEXT NOT NULL,
  "updated_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "approval_status" TEXT NOT NULL DEFAULT 'not_required';

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "approval_note" TEXT;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "approved_by" TEXT;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "approved_at" TEXT;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "evidence_link" TEXT;

ALTER TABLE "training_completions" ADD COLUMN IF NOT EXISTS "evidence_file_url" TEXT;
