-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 28
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 28.

CREATE TABLE IF NOT EXISTS "enhancements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "priority" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "submitted_by_name" TEXT NOT NULL,
  "submitted_by_email" TEXT,
  "approved_by_name" TEXT,
  "approved_at" TEXT,
  "manager_notes" TEXT,
  "target_quarter" TEXT,
  "updated_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
