-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 29
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 29.

ALTER TABLE "enhancements" ADD COLUMN IF NOT EXISTS "platform" TEXT NOT NULL;
