-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 30
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 30.

ALTER TABLE "enhancements" ADD COLUMN IF NOT EXISTS "legacy_id" TEXT;
