-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 31
-- Name:    3 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 31.

ALTER TABLE "enhancements" ADD COLUMN IF NOT EXISTS "assignee_name" TEXT;

ALTER TABLE "enhancements" ADD COLUMN IF NOT EXISTS "assignee_email" TEXT;

ALTER TABLE "enhancements" ADD COLUMN IF NOT EXISTS "updates_json" TEXT;
