-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 32
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 32.

CREATE TABLE IF NOT EXISTS "celebrations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "person_name" TEXT NOT NULL,
  "event_type" TEXT NOT NULL,
  "event_month" INTEGER NOT NULL,
  "event_day" INTEGER NOT NULL,
  "event_year" INTEGER,
  "notes" TEXT,
  "created_by" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
