-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 33
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 33.

CREATE TABLE IF NOT EXISTS "noc_mttr_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_size_bytes" INTEGER,
  "uploaded_by" TEXT,
  "selected_sheet_name" TEXT,
  "selected_customer_column" TEXT,
  "selected_month_column" TEXT,
  "selected_mttr_column" TEXT,
  "parsed_json" TEXT NOT NULL,
  "row_count" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
