-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 34
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 34.

CREATE TABLE IF NOT EXISTS "performance_discussions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "manager_name" TEXT NOT NULL,
  "cycle_label" TEXT NOT NULL,
  "period_start" TEXT NOT NULL,
  "period_end" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "scheduled_date" TEXT,
  "discussion_date" TEXT,
  "overall_summary" TEXT,
  "strengths" TEXT,
  "growth_areas" TEXT,
  "manager_notes" TEXT,
  "employee_commitments" TEXT,
  "metrics_snapshot_json" TEXT,
  "updated_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
