-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 35
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 35.

CREATE TABLE IF NOT EXISTS "performance_discussion_submissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_name" TEXT NOT NULL,
  "cycle_label" TEXT NOT NULL,
  "period_start" TEXT NOT NULL,
  "period_end" TEXT NOT NULL,
  "submission_status" TEXT NOT NULL,
  "opening_notes" TEXT,
  "business_impact_notes" TEXT,
  "behaviors_notes" TEXT,
  "feedback_notes" TEXT,
  "engagement_notes" TEXT,
  "development_notes" TEXT,
  "second_half_priorities" TEXT,
  "closing_summary" TEXT,
  "overall_summary" TEXT,
  "employee_commitments" TEXT,
  "metrics_snapshot_json" TEXT,
  "submitted_at" TEXT,
  "updated_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
