-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 36
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 36.

CREATE TABLE IF NOT EXISTS "manager_feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "feedback_from" TEXT NOT NULL,
  "feedback_for" TEXT NOT NULL,
  "ticket_number" TEXT,
  "comment" TEXT NOT NULL,
  "submitted_by" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
