-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 39
-- Name:    3 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 39.

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "approval_status" TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "approved_by" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "approved_at" TEXT;
