-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 40
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 40.

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_comment" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_comment_by" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_comment_at" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_read_at" TEXT;
