-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 41
-- Name:    2 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 41.

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_acknowledged_at" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "recipient_acknowledged_by" TEXT;
