-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 42
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 42.

CREATE TABLE IF NOT EXISTS "work_allotment_jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operational_date" TEXT NOT NULL,
  "post_date" TEXT NOT NULL,
  "shift" TEXT NOT NULL,
  "primary" TEXT,
  "backup" TEXT,
  "nt_primary" TEXT,
  "message" TEXT NOT NULL,
  "next_primary" TEXT,
  "next_post_time" TEXT,
  "continuing_from" TEXT,
  "carry_path_used" TEXT,
  "carry_path_rule" TEXT,
  "available_members_json" TEXT,
  "post_time_label" TEXT NOT NULL,
  "post_at" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "slack_ts" TEXT,
  "last_error" TEXT,
  "generated_at" TEXT NOT NULL,
  "posted_at" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
