-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 43
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 43.

CREATE TABLE IF NOT EXISTS "work_allotment_automation_runs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action" TEXT NOT NULL,
  "ran_at" TEXT NOT NULL,
  "generation_triggered" BOOLEAN,
  "generation_skipped" BOOLEAN,
  "due_count" INTEGER,
  "posted_count" INTEGER,
  "failure_count" INTEGER,
  "note" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
