-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 44
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 44.

CREATE TABLE IF NOT EXISTS "ownership_tasks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_type" TEXT NOT NULL,
  "dedupe_key" TEXT NOT NULL,
  "operational_date" TEXT NOT NULL,
  "assignee_name" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "details" TEXT,
  "source_shift" TEXT,
  "off_members_json" TEXT,
  "status" TEXT NOT NULL,
  "completed_at" TEXT,
  "start_at" TEXT,
  "next_reminder_at" TEXT,
  "last_reminded_at" TEXT,
  "reminder_interval_minutes" INTEGER,
  "reminder_count" INTEGER,
  "slack_user_id" TEXT,
  "last_error" TEXT,
  "created_by" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
