-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 45
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 45.

CREATE TABLE IF NOT EXISTS "finance_cases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "month_key" TEXT NOT NULL,
  "case_number" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "created_by" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
