-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 46
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 46.

ALTER TABLE "finance_cases" ADD COLUMN IF NOT EXISTS "service" TEXT NOT NULL DEFAULT 'mobility';
