-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 47
-- Name:    3 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 47.

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "screenshot_name" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "screenshot_type" TEXT;

ALTER TABLE "manager_feedback" ADD COLUMN IF NOT EXISTS "screenshot_data_url" TEXT;
