-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 48
-- Name:    1 change
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 48.

CREATE TABLE IF NOT EXISTS "work_allotment_asrh_hours" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "month_key" TEXT NOT NULL,
  "date_key" TEXT NOT NULL,
  "member_name" TEXT NOT NULL,
  "hours" REAL NOT NULL,
  "source" TEXT NOT NULL,
  "notes" TEXT,
  "updated_by" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
