// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth — extended to be compatible with
// useIdentity() which expects { authenticated, name, role, email, picture }.

import type { IncomingMessage, ServerResponse } from "node:http";
import { loadSession } from "./_lib/session.js";
import { defaultRoleFor, lookupByEmail } from "../_lib/roles.js";

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const session = await loadSession(req);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");

  if (!session) {
    res.end(JSON.stringify({ authenticated: false, user: null }));
    return;
  }

  // Role is stored in the encrypted payload (set by callback.ts).
  // Fall back to roster lookup by email, then by name.
  const anySession = session as Record<string, unknown>;
  const role: string =
    (typeof anySession.role === "string" ? anySession.role : null) ??
    lookupByEmail(String(session.email ?? "").toLowerCase())?.role ??
    defaultRoleFor(session.name ?? "");

  const name = session.name ?? null;
  const email = session.email ?? null;
  const picture = session.picture ?? null;

  res.end(JSON.stringify({
    // Shape expected by useIdentity()
    authenticated: true,
    name,
    role,
    email,
    picture,
    // Shape expected by AuthProvider / useAuth()
    user: {
      id: session.sub,
      email,
      name,
      picture,
      provider: session.provider,
    },
  }));
}
